### ISSUE TITLE
Async load data from WEB API into grid editor.

### ISSUE THREAD

**Issue by YadavAvinashK** [ghiscoding/Angular-Slickgrid#46] opened 2018-06-27 06:48 UTC
Hello,

Am trying to populate grids columns value from HTTP get request data and use Single/Multiple select on it. For different columns different database table output is to be mapped.
How this http data is to be mapped to the collections in the column?

**Comment by ghiscoding** [comment] 2018-06-27 13:35
There's multitude of Wikis that provide examples for a lot of things. So please read the [Wiki - HOWTO](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step). The only thing you need to do is to fill the `dataset` property with JSON data with an http `subscribe`

**Comment by YadavAvinashK** [comment] 2018-06-27 13:41
Am clear with populating the dataset with json by subscribe. Am asking about applying Single/multiple select editor on column and populating columns value from json??

**Comment by ghiscoding** [comment] 2018-06-27 14:03
Again there's a lot of example and Wikis, the only limitation is that your collections for the Filters and Editors **must** exist **before** creating them. Basically there's no async feature for them, that is a SlickGrid limitation. If you need to load the collections in an async fashion, you will have to use Angular Resolver, which is what we do in our own project.

**Comment by ghiscoding** [comment] 2018-06-27 18:13
duplicate of #39

**Closed by ghiscoding** 2018-06-27 18:13 UTC

**Comment by ghiscoding** [comment] 2018-08-14 00:06
This feature is now available in [version 1.4.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v1.4.0)

If you haven't yet voted, please do ⭐️ 
Cheers
