### ISSUE TITLE
Tree Data Sort order is not kept when adding a new item

### ISSUE THREAD

**Issue by kiranbangar5946** [ghiscoding/Angular-Slickgrid#1423] opened 2024-06-04 12:20 UTC
### Describe the bug

For tree data structure with one parent and two childs.
Step 1 - 
Sort column by asc or desc value

Step 2 - 
As soon as any new data(row) comes in it resorts it according to default behaviour.

### Reproduction

For tree data structure with one parent and two childs.
Step 1 - 
Sort column by asc or desc value

Step 2 - 
As soon as any new data(row) comes in it resorts it according to default behaviour.

### Expectation

It should adhere to the sorting which is selected by user rather then sorting it to default behaviour when new data comes in.

### Environment Info

```shell
angular-slickgrid@5.6.4
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Quick Start](https://ghiscoding.gitbook.io/angular-slickgrid/getting-started/quick-start).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment] 2024-06-04 17:43
I can replicate the problem but there's a few things to note:
- I will only apply fixes for current major version (which is currently 8.x)
- you might be surprised but SlickGrid itself doesn't support Tree Data, it only supports flat data. I manage to bring Tree Data into SlickGrid by keeping 2 copies of data (a flat array and a hierarchical array), so anytime something changes then the flat dataset must be recreated and resorted... and for this use case (bug), it was assuming to always resort in ascending order all the time
- you can probably apply a temporary fix by saving a ref to the current Sorts from Grid State, then add the new item and finally call a Sort by using `this.angularGrid.sortService.updateSorting()` with previous Grid State Sorts (see [Example 4](https://ghiscoding.github.io/Angular-Slickgrid/#/clientside) to apply dynamic sort)

**Comment by jano-kucera** [comment] 2024-06-05 04:17
I'm not sure if it's related, but I had an issue where adding stuff to the dataset in grid's hierarchical mode was resulting in children duplicates. I patched the behavior as follows (the grid was already constructed from flat data and the [childrenPropName] field was not cleared properly when reusing the dataset after changes):
![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/129259868/958727a9-e5fa-4b1b-8a77-95950d53f944)

**Comment by ghiscoding** [comment] 2024-06-05 04:47
@jano-kucera it's unrelated and I found the problem and will push a fix tomorrow with updated unit tests. For your use case, I'd be happy to receive a PR in Slickgrid-Universal with this fix, however it would be helpful to get a way to reproduce the bug you are describing (which is totally different). I'll be pushing a new release by the weekend, so a PR with your fix before then would be great. Thanks

**Comment by jano-kucera** [comment] 2024-06-05 05:00
I was thinking about creating PR for that, but I'm using the hierarchical grid with the backend dataset and I've done multiple patches for that to work. Thus I'm not certain if this is behavior that happens to everyone/someone might actually rely on that.

**Comment by ghiscoding** [comment] 2024-06-05 05:10
@jano-kucera yeah well I need a way to reproduce because yeah we want to make sure that it's not just for you and maybe also update unit tests for them. 

For the issue mentioned here, I've created the PR in Slickgrid-Universal [PR 1558](https://github.com/ghiscoding/slickgrid-universal/pull/1558) but I still need to add more unit tests. I'll do that tomorrow since it's getting late here.

@jano-kucera so the best would really be to have a repro in any of the existing examples. I also added Stackblitz not long ago, so it's easier to create a repro using Stackblitz. You mention that you're using it with backend, but as you probably know the Tree Data will only work with existing data (what the DataView has), so are you pulling all data (maybe in a lazy way)? Anyway, any issue you may find, please contribute a PR when possible. Cheers

**Comment by ghiscoding** [comment] 2024-06-08 14:39
closed by #1425 and fix available in [v8.1.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v8.1.0)

**Closed by ghiscoding** 2024-06-08 14:39 UTC
Labels: bug, slickgrid-universal, has PR, upstream

**Comment by ghiscoding** [comment] 2024-10-14 04:06
> I was thinking about creating PR for that, but I'm using the hierarchical grid with the backend dataset and I've done multiple patches for that to work. Thus I'm not certain if this is behavior that happens to everyone/someone might actually rely on that.

I was re-reading your comment and was wondering how you got tree data working with a backend? I mean I purposely added a warning saying that I don't support it simply because I thought it was too much work and so I'm wondering how did you get it work and what does it look like? I for sure would be happy to receive any PRs bringing support for this feature.

**Comment by jano-kucera** [comment] 2024-10-14 04:14
@ghiscoding Filtering and sorting are done only server-side, the server returns a flat dataset, I pass it to your Slickgrid with the given parentId property name to construct the hierarchical view. Each filter/sort change from the grid already has events firing, I just subscribe to them and reload the dataset with new params. It performs quite well in this simple implementation. So in the end it's the same as not-hierarchical data, I just filter and sort server side :)

**Comment by ghiscoding** [comment] 2024-10-14 04:20
@jano-kucera ok but what about Pagination? Pagination was mainly the reason I disabled tree data with backend services. Unless you're purposely loading a larger page size to avoid such problems?

**Comment by jano-kucera** [comment] 2024-10-14 04:21
Oh and for paging - we have a few custom paging behaviors for different screens
- no paging (server returns all the data)
- fixed count of children (each parent row always has X children, so just load 50*X rows, the next pages we just append to the dataset
- lazy loaded children - we load 50 parents, set HAS_CHILDREN_PROP to true, so it looks like parent row and on row expand we lazy load the children, append to the flat dataset

**Comment by ghiscoding** [comment] 2024-10-14 04:28
yeah ok that is what I thought you might have been doing, so you mentioned that your slickgrid might have been modified, is that the case? I again would be happy to receive any PRs if it helps with the feature, it would also be nice to get a working example, even though that might be long or hard to provide.

**Comment by jano-kucera** [comment] 2024-10-14 04:43
There is one patch for initial sorting which we did not want, so that's just suppressed atm. And that should be optional from some version if I'm correct, I think I read it in some changelog.

Once we upgrade the Slickgrid I will revise the patched behavior and create PRs if what's left is still relevant.

**Comment by ghiscoding** [comment] 2024-10-14 04:47
great thanks
