### ISSUE TITLE
sorting and filtering doesn't work after row movement

### ISSUE THREAD

**Issue by mohit4834** [ghiscoding/Angular-Slickgrid#115] opened 2019-01-24 10:58 UTC
**I'm submitting a bug report**

**Current behavior:**
I am using angular slickgrid functionalities like client side filtering and sorting with row movement. Once i move the row. It doesn't sort or filter data anymore. Until i move the row it works fine.

**Expected/desired behavior:**
I think Sorting and filtering should  works fine after the row movement. It should be independent and works in all scenarios.

* **What is the expected behavior?**
I think Sorting and filtering should  works fine after the row movement. It should be independent and works in all scenarios.

* **What is the motivation / use case for changing the behavior?**
what if my user want to sort or filter data after the row movement.

**Comment by ghiscoding** [comment] 2019-01-24 14:22
I don't understand what you mean by row movement? If you mean changing the row position, it works fine on this [example](https://ghiscoding.github.io/angular-slickgrid-bs4-demo/#/clientside)

![2019-01-24_09-20-55](https://user-images.githubusercontent.com/643976/51684153-7abb0b00-1fb9-11e9-9d9f-fc70839da025.gif)

**Comment by mohit4834** [comment] 2019-01-29 05:16
Hi @ghiscoding ,

Please excuse for the delay.

i am still not able to resolve the issue. if we use our Row move functionality [rowMove](https://ghiscoding.github.io/angular-slickgrid-bs4-demo/#/rowmove). We can see it here. If we implement the sorting and filtering with the rowMove functionality. After the movement of rows we can't perform sorting or filtering upon it. It doesn't works anymore.
Please guide me, how we can approach and resolve it.

Thanks & Regards,
Mohit Goyal.

**Comment by ghiscoding** [comment] 2019-01-29 15:41
I still don't understand what you mean, I posted an animated gif earlier showing that it works fine from my perspective. If you meant something else, then please provide an animated gif of the issue

**Comment by ghiscoding** [comment] 2019-02-06 14:28
I will close this since no real reproducible example or animated gif was provided, I also don't think there's any problem with the lib itself. Closing but I can re-open if necessary.

**Closed by ghiscoding** 2019-02-06 14:28 UTC
Labels: cannot replicate, needs more info, question
