### ISSUE TITLE
Issue in drag

### ISSUE THREAD

**Issue by sreenithalbhat** [ghiscoding/Angular-Slickgrid#267] opened 2019-08-16 11:49 UTC
### Your Environment
Issue in tablet and responsive screen while am trying to scroll.Can you please help

Angular | ^6.0.3
Angular-Slickgrid | ^1.9.6
TypeScript | ~2.7.2

| Operating System  |
| NPM/Node/Yarn     |

### Context
core.js:1598 ERROR TypeError: Cannot read property 'top' of null
    at CellRangeDecorator.show (slick.cellrangedecorator.js:51)
    at SlickGrid.handleDragStart (slick.cellrangeselector.js:115)
    at Event.notify (slick.core.js:147)
    at trigger (slick.grid.js:2038)
    at HTMLDivElement.handleDragStart (slick.grid.js:3880)
    at HTMLDivElement.dispatch (jquery-3.2.1.slim.min.js:3)
    at HTMLDivElement.push../node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js.$event.dispatch (jquery.event.drag-2.3.0.js:382)
    at HTMLDivElement.<anonymous> (jquery.event.drag-2.3.0.js:267)
    at Function.each (jquery-3.2.1.slim.min.js:2)
    at r.fn.init.each (jquery-3.2.1.slim.min.js:2)

**Comment by ghiscoding** [comment] 2019-08-16 13:26
Sorry but there is not much we can do about that, dragging on tablet is just not supported because jQuery Event Drag just doesn't support it. That was designed 10 years ago, even before tablet existed, the libraries that are in SlickGrid core are not designed for newer technologies... so the final is No that is not and won't be supported, just don't use drag on a table.

**Closed by ghiscoding** 2019-08-16 13:26 UTC
Labels: core lib, wontfix

**Comment by sreenithalbhat** [comment] 2019-08-19 04:27
> Sorry but there is not much we can do about that, dragging on tablet is just not supported because jQuery Event Drag just doesn't support it. That was designed 10 years ago, even before tablet existed, the libraries that are in SlickGrid core are not designed for newer technologies... so the final is No that is not and won't be supported, just don't use drag on a table.

@ghiscoding Thankyou

**Comment by sreenithalbhat** [comment] 2019-08-19 04:29
Also Does the angular slickgrid compatible in mobile devices?

**Comment by ghiscoding** [comment] 2019-08-19 13:17
The answer is the same, it works on mobile but there are certain functionalities that just won't work like the column drag & drop. This grid was built for desktop first, there are some tweak that you need to do for a good mobile experience, for example set a `minWidth` to all your columns, for the rest it should work, the Grid Menu will probably be really useful on mobile to show/hide columns

**Comment by sreenithalbhat** [comment] 2019-08-20 05:27
Edit functionality was not working on my editor while i open in app.Found the same issue in Editor example too.text box was getting closed when i click not able to edit

https://ghiscoding.github.io/Angular-Slickgrid/#/angular-components
