### ISSUE TITLE
 No provider for TranslateService!

### ISSUE THREAD

**Issue by harryhahn** [ghiscoding/Angular-Slickgrid#24] opened 2018-04-05 11:18 UTC
we use electron, ng 5x and ngx-translate 10x
we following the Step by step instructions (step 5 minimal Setup)

when we use the grid
the following error occurs and we do not know how to fix it.

`core.js:1448 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[AngularSlickgridComponent -> TranslateService]: 
  StaticInjectorError(Platform: core)[AngularSlickgridComponent -> TranslateService]: 
    NullInjectorError: No provider for TranslateService!
Error: StaticInjectorError(AppModule)[AngularSlickgridComponent -> TranslateService]: 
  StaticInjectorError(Platform: core)[AngularSlickgridComponent -> TranslateService]: 
    NullInjectorError: No provider for TranslateService!
    at _NullInjector.webpackJsonp../node_modules/@angular/core/esm5/core.js._NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.webpackJsonp../node_modules/@angular/core/esm5/core.js.StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.webpackJsonp../node_modules/@angular/core/esm5/core.js.StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at _createClass (core.js:10891)
    at _createProviderInstance$1 (core.js:10865)
    at _NullInjector.webpackJsonp../node_modules/@angular/core/esm5/core.js._NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.webpackJsonp../node_modules/@angular/core/esm5/core.js.StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.webpackJsonp../node_modules/@angular/core/esm5/core.js.StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at _createClass (core.js:10891)
    at _createProviderInstance$1 (core.js:10865)
    at resolvePromise (zone.js:809)
    at resolvePromise (zone.js:775)
    at zone.js:858
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4740)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at <anonymous>`

**Comment by ghiscoding** [comment] 2018-04-05 13:03
It looks like you are missing `ngx-translate` which is a dependency
```javascript
No provider for TranslateService! at 
```

There might be more info in this [Wiki - Localization](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Localization) page.

**Comment by vseyedzadeh** [comment] 2018-04-12 15:39
I have the same error 
NullInjectorError: No provider for TranslateService!
 I installed ngx-translate and did everything in step by step document but when I use the grid this error occurs!!
I searched a lot but I'm really confused. :(

**Comment by ghiscoding** [comment] 2018-04-12 15:46
@vseyedzadeh 
Have you took a look at my [Angular-Slickgrid-demo](https://github.com/ghiscoding/Angular-Slickgrid-demo/blob/master/src/app/app.module.ts) repo? It is a separate App and uses Angular-Slickgrid from the `package.json` file just like any other App.

**Comment by vseyedzadeh** [comment] 2018-04-12 16:51
Yes I did. but my problem is when I add Slickgrid to my exist project by npm install --save angular-slickgrid and use the grid this error occurs. I also checked the dependencies and it seems every things is  installed!
This is app.Module. I don't have localisation in my project but I installed  ngx-translate since it was a dependency.
Thanks in advance for your help.

import { BrowserModule } from '@angular/platform-browser';

import { GridBasicComponent } from './grid-basic/grid-basic.component';

import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Injector, APP_INITIALIZER, NgModule } from '@angular/core';
import { LOCATION_INITIALIZED } from '@angular/common';
import { TranslateModule, TranslateLoader, TranslateService } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';



import { AppComponent } from './app.component';
import { AngularSlickgridModule } from 'angular-slickgrid';

// AoT requires an exported function for factories
export function createTranslateLoader(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

// use an Initializer Factory as describe here: https://github.com/ngx-translate/core/issues/517#issuecomment-299637956
export function appInitializerFactory(translate: TranslateService, injector: Injector) {
  return () => new Promise<any>((resolve: any) => {
    const locationInitialized = injector.get(LOCATION_INITIALIZED, Promise.resolve(null));
    locationInitialized.then(() => {
      const langToSet = 'en';
      translate.setDefaultLang('en');
      translate.use(langToSet).subscribe(() => {
        // console.info(`Successfully initialized '${langToSet}' language.'`);
      }, err => {
        console.error(`Problem with '${langToSet}' language initialization.'`);
      }, () => {
        resolve(null);
      });
    });
  });
}

@NgModule({
  declarations: [
    AppComponent,

    GridBasicComponent

  ],
  imports: [

    BrowserModule,
    HttpClientModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpClient]
      }
    }),
    AngularSlickgridModule.forRoot({
      enableAutoResize: true
    })
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: appInitializerFactory,
      deps: [TranslateService, Injector],
      multi: true
    }],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by ghiscoding** [comment] 2018-04-12 18:20
@vseyedzadeh 
Yes `ngx-translate` is a dependency, that will be until `Angular` has a better `i18n` support for dynamic translation. I heard it might come in Angular 6, we shall see. Until then, `ngx-translate` it is.

Not sure if it's really your App module but a lot of your `imports` are empty and that will never work.
All your `from ''` are empty.
```javascript
import { HttpClient, HttpClientModule } from '/http';
import { Injector, APP_INITIALIZER, NgModule } from '';
import { LOCATION_INITIALIZED } from '';
import { TranslateModule, TranslateLoader, TranslateService } from '';
import { TranslateHttpLoader } from '';
```
It should be something like this (which is in the [wiki - Localization - appModule](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Localization#app-module-1) section
```javascript
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Injector, APP_INITIALIZER, NgModule } from '@angular/core';
import { LOCATION_INITIALIZED } from '@angular/common';
```

Also, I just saw that I missed 2 imports in that Localization section, I just added them, they are the following:
```javascript
import { TranslateModule, TranslateLoader, TranslateService } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
```

**Comment by vseyedzadeh** [comment] 2018-04-12 18:45
I checked the App module. all the imports are Ok. I also have the last 2 imports for localization. but It still doesn't work.

**Comment by ghiscoding** [comment] 2018-04-12 20:26
Can you try to download the [Angular-Slickgrid demo](https://github.com/ghiscoding/Angular-Slickgrid-demo) and try building and running it.

**Comment by ghiscoding** [comment] 2018-04-30 15:06
I didn't get confirmation feedback but I'm quite sure this is now fixed with the info I wrote in previous post, so I'm closing it

**Closed by ghiscoding** 2018-04-30 15:06 UTC

**Comment by coolrb** [comment] 2019-06-24 12:47
I am still clueless about this error. My environment

> Angular CLI: 7.0.2
Node: 10.14.2
OS: darwin x64
Angular: 7.2.15
"@ngx-translate/core": "^11.0.1",
"@ngx-translate/http-loader": "^4.0.0",
"angular-slickgrid": "^2.9.0",

**Comment by ghiscoding** [comment] 2019-06-24 18:09
@coolrb 
This issue was closed long time ago, there was an issue at the time but that is no longer a problem.

In your case, it's most probably a problem with your setup, there are plenty of resources for you to look into, for example [HOWTO - Wiki](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step), [Localization - Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Localization), [Angular-Slickgrid BS4 demo](https://github.com/ghiscoding/angular-slickgrid-bs4-demo) repo and unless you provide any code to reproduce, I cannot help you.

**Comment by coolrb** [comment] 2019-06-24 18:46
@ghiscoding 
Thanks for your pointer. I finally decided to work with material table component https://material.angular.io/components/table/examples
But I will again try slickgrid in our next release
