### ISSUE TITLE
Grid auto resizing issue.

### ISSUE THREAD

**Issue by mohit4834** [ghiscoding/Angular-Slickgrid#119] opened 2019-01-29 07:55 UTC
**I'm submitting a feature request**

**Current behavior:**
Dynmaic Grid resizing doesn't work properly. I have a collapsible nav bar in my application when i collapse the nav bar. My grid should automatically resize and took the width of my available screen. When i load my grid on the smaller window it comes small and when i expand my browser widow it should ideally resize but its not happening. I have set properties in grid options like this : 

```ts
gridOptions = {
      autoResize: {
        containerId: 'gridDiv',
        minHeight: 300,
        minWidth: 500,
        maxWidth: document.getElementById('gridDiv').offsetWidth,
        // maxHeight: 500,
        sidePadding: 0
      },
      editable: false,
      autoFitColumnsOnFirstLoad: true,
      enableAutoSizeColumns: true,
      enableFiltering: true,
      enableSorting: true,
      enableHeaderMenu: false,
      enableAutoResize: true,
      alwaysShowVerticalScroll: false,
      enableRowMoveManager: true,
      enableCheckboxSelector: true,
      enableRowSelection: true,
      checkboxSelector: {
        // remove the unnecessary "Select All" checkbox in header when in single selection mode
        hideSelectAllCheckbox: false,
        hideInFilterHeaderRow: false,
        hideInColumnTitleRow: true
      },
      rowSelectionOptions: {
        // True (Single Selection), False (Multiple Selections)
        selectActiveRow: false
      },
      enableGridMenu: false,
      rowMoveManager: {
        onBeforeMoveRows: (e, args) => this.onBeforeMoveRow(e, args),
        onMoveRows: (e, args) => this.onMoveRows(e, args),
      }
    };
```

Here gridDiv is the id of div in which i have placed my grid.
Please guide me where i have done something wrong.

**Expected/desired behavior:**
Grid should resize when i resize my window.

* **What is the expected behavior?**
Grid should resize when i resize my window. Or when available space for the grid is increased or decreased.

* **What is the motivation / use case for changing the behavior?**
I need this functionality in my application. As it gives us great interactive User Interface.

**Comment by ghiscoding** [comment] 2019-01-29 15:45
There are plenty of examples and almost all of them use auto-resize, please refer to them to fix your issue. This issue is all about questions, not real issues. Please look carefully in all the examples and all the Wikis

**Comment by ghiscoding** [comment] 2019-02-06 14:29
I will close since no reproducible code was provided, I also don't think there's any problem with the lib itself. Closing but I can re-open if necessary.

**Closed by ghiscoding** 2019-02-06 14:29 UTC
Labels: cannot replicate, question
