### ISSUE TITLE
Current row values getting updated in the above row with latest Chrome Version 128.0.6613.120 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by pavanmajji03** [ghiscoding/Angular-Slickgrid#1468] opened 2024-09-09 16:26 UTC
### Describe the bug

```
Chrome Version 128.0.6613.120 (Official Build) (64-bit)
OS: Windows 10
Angular version: 15
angular-slickgrid: 5.6.4
```

### Reproduction

1. Edit a cell value in row
2. Click Enter 

Actual:
The value is getting updated in the above cell in above row
![image](https://github.com/user-attachments/assets/652a84dc-1824-4216-8fbb-94cd56fc8c01)
![image](https://github.com/user-attachments/assets/7373794a-d50c-42a9-8cc5-1a422112846c)

### Expectation

The value should get updated in the same cell in same row

### Environment Info

```shell
Chrome Version 128.0.6613.120 (Official Build) (64-bit)
OS: Windows 10
Angular version: 15
angular-slickgrid: 5.6.4
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Quick Start](https://ghiscoding.gitbook.io/angular-slickgrid/getting-started/quick-start).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment] 2024-09-09 17:22
Unless you provide a full repro, I will close this issue. There are plenty of unit tests and E2E tests covering editing, I would be surprised of any issues. You should make sure that the Ids that you are editing are the expected ones.

**Comment by pavanmajji03** [comment] 2024-09-09 18:04
Yes I agree, you wouldn't support but I want to fix this in my application anyhow.
Can we connect if possible on any channel or somewhere if you suggest, I have debugged a detail and found some things.
It would be really great if we could connect, but give me some time to have stackblitz or some sort of reproduction.

And as well is there a problem for the marking the current row if the method `getBoundingClientRect()` dosent give the correct y value.
Because I observed in previous version of the chrome and current version of the chrome I am getting a difference of ~15px for y position
  ref:[chrome issue which might relate to above]( https://issues.chromium.org/issues?q=status:open%20getBoundingClientRect)

**Comment by ghiscoding** [comment] 2024-09-09 19:11
This is an Open Source project, I am not being paid for this and so I am not available via any channels. You need to provide a full repro or I just won't help (sorry but I already spent way too much time on this free project).

You can simply open the Stackblitz link on the main readme page, then open any of the example and reproduce the error you're having and that is the way to provide a full repro.

![image](https://github.com/user-attachments/assets/e67fea87-bb8d-4b66-b6d2-31e7ea80345f)

**Comment by pavanmajji03** [comment] 2024-09-11 08:17
@ghiscoding 
Issue reproduced even on the latest version, attached the recording.

Uploading Issue-reproduction-slickgrid.mp4…

Please check and do let me know if there any solution for this

**Comment by pavanmajji03** [comment] 2024-09-11 08:19
@ghiscoding 
Issue reproduced even on the latest version, attached the recording.

https://github.com/user-attachments/assets/27a4c48b-0e98-4fa2-8d28-2ffe47cc19eb



Please check and do let me know if there any solution for this problem

**Comment by ghiscoding** [comment] 2024-09-12 05:28
You're purposely changing the body zoom level and it was never mentioned in your issue until I saw it in the video, so your issue wasn't filled in correctly. However, the question is why are you doing this? Is it really the only approach that you have?

Because the problem is that SlickGrid relies on the row height (that can also be changed via the grid options) to do lots of internal stuff, for example it uses it to find the row of the cell you clicked and when you change the zoom level then you are screwing up all these calculations. For example, the cell edit that you're having difficulties with we would have to change the code with something like this

https://github.com/ghiscoding/slickgrid-universal/blob/7a6dd0659cb425af59a68c1f7a08241f987a5505/packages/common/src/core/slickGrid.ts#L3260C3-L3262C4

```diff
protected getRowFromPosition(y: number): number {
-    return Math.floor((y + this.offset) / this._options.rowHeight!);
+   const zoom = parseInt(document.body.style.zoom) || 100;
+   const currentRowHeight = this._options.rowHeight! / 100 * zoom;
+   return Math.floor((y + this.offset) / currentRowHeight);
}
```
but that is just 1 fix, and like I said SlickGrid relies on these calculations to do a lot of stuff (find row by x,y coordinates, row selection, row dragging, etc...), so not just the editing as you can see. 

If however you use the browser zoom then it works fine.

I don't really know what to say here, I think that you're looking for trouble by playing with the zoom and if we want the lib to support it then there would 50 lines of code to look into and I can't be 100% sure to cover them all. I'm not sure that I want to proceed with such change and even if I do, I will only fix latest version so even if I fix it, you won't get the fix until you upgrade yourself to the latest version (unless you npm patch the lib)

@zewa666 do you have any suggestions on this matter?

**Comment by pavanmajji03** [comment] 2024-09-12 05:43
@ghiscoding 
Thank you for the reply

Yes, in the application the setup was such a way on the zoom, so I figured this cause after I raised the issue. 
-

But just wanted to call out one important thing,
This same scenario works perfectly fine in older version of chrome/ edge browsers without a problem
as internally this package uses getBoundingClientRect() which is providing a different result when compared to older version when the y, top values were not changing drastically with the zoom style setting.

Which brought me raise an issue in chromium project as well
Ref to the issue: [https://issues.chromium.org/issues/365913984](https://issues.chromium.org/issues/365913984)

And also I have created a stackblitz to showcase the same scenario.
Ref: [https://stackblitz.com/edit/vitejs-vite-mqasgn?file=main.js](https://stackblitz.com/edit/vitejs-vite-mqasgn?file=main.js)

Hope this adds on or helps to take a right decision for your changes

CC: @zewa666

**Comment by zewa666** [comment] 2024-09-12 06:06
I agree that supporting different zoom levels would be out of scope here as the core library itself doesnt respect it. but also neither most likely do other dependencies you bet on in combo with slickgrid related to positioning.

my take would be to add an init check if the zoom level is changed and console.warn the user about subpar support for that.

**Comment by ghiscoding** [comment] 2024-09-13 02:48
I took another look and tried to do some code changes to support it but quickly realized that there's a lot of indirect issues and so I agree with @zewa666 and I will **not support** a zoom level that is not 100% and simply show a console warning via this Slickgrid-Universal [PR 1676](https://github.com/ghiscoding/slickgrid-universal/pull/1676)

**Closed by ghiscoding** 2024-09-13 02:48 UTC
Labels: won't fix, unsupported version
