### ISSUE TITLE
Bug: Sorting does not pick Added/removed row

### ISSUE THREAD

**Issue by Royalg007** [ghiscoding/Angular-Slickgrid#110] opened 2019-01-18 14:28 UTC
* **Angular Version:**
angular version ^7

* **Library Version:**
angular-slickgrid": "^2.1.5

* **Browser:**
all | Chrome XX 

**Current behavior:**
 Added row does show not after sorting/filtering in grid.
 Deleted row comes back after sorting/filtering in grid.

operation:
gridService.addItemToDatagrid(item, true);
gridService.deleteDataGridItem(item);

URL: Issue comes in demo also:
https://ghiscoding.github.io/angular-slickgrid-bs4-demo/#/additem 

**Expected/desired behavior:**

Grid Data view should be updated properly for sorting/filtering after add/remove row operation.

* **What is the motivation / use case for changing the behavior?**

moving rows from left to right grid.

**Comment by ghiscoding** [comment] 2019-01-18 14:57
The thing is that I don't personally like the grid to be resorted after adding a row in the grid (because it could be anywhere in the grid and I also don't want to scroll to that row once inserted). I prefer to add it on `index[0]` (first row) of the grid and that is the behavior that it's currently doing.

**Comment by ghiscoding** [comment] 2019-01-21 21:47
I added a 3rd argument `shouldResortGrid` boolean to the methods `addItemToDatagrid` and `addItemToDatagrids` to call the dataview resort (which I explained earlier) to make it more convenient for you. You can see this print screen of this new argument.

![grid_add_item_new_argument](https://user-images.githubusercontent.com/643976/51500409-d90aa280-1d9b-11e9-85da-377dcf31189b.png)

As for the potential bug that you reported, I cannot reproduce it. I use the new argument `shouldResortGrid` to resort and tried to add 2 new rows (Task 1000 and 1001) with the grid sorted by Task, then delete 1 row (Task 1000) and resort and I don't see the row that I deleted (Task 1000), it stays deleted. See below. 

![2019-01-21_15-59-42](https://user-images.githubusercontent.com/643976/51500493-22f38880-1d9c-11e9-87f6-6d34a7109d7e.gif)

**Comment by ghiscoding** [comment] 2019-01-26 19:54
Closing as this was addressed by updating some of the methods. Since I got no feedback, I will consider "no news, good news" and I'll close the issue. I can reopen if need be.

Lastly, if you like the lib, you can up vote ⭐️ to raise popularity of the lib.
Thanks

**Closed by ghiscoding** 2019-01-26 19:54 UTC
Labels: enhancement, needs more info
