### ISSUE TITLE
Angular 8 support?

### ISSUE THREAD

**Issue by tannenbaums** [ghiscoding/Angular-Slickgrid#266] opened 2019-08-12 22:25 UTC
## Software | Version(s)

Angular | 8.2.0
Angular-Slickgrid | 2.9.9

## Context
Just upgraded from 7.2.1  to Angular 8 but angular-slickgrid stopped working 

## Expected Behavior

Current Behavior
It throws an exception:
```
CaseListingComponent.html:16 ERROR ReferenceError: preHeaderH is not defined
    at getViewportHeight (slick.grid.js:2903)
    at SlickGrid.finishInitialization [as init] (slick.grid.js:492)
    at AngularSlickgridComponent.initialization (angular-slickgrid.js:11983)
    at AngularSlickgridComponent.ngAfterViewInit (angular-slickgrid.js:11941)
    at callProviderLifecycles (core.js:26694)
    at callElementProvidersLifecycles (core.js:26659)
    at callLifecycleHooksChildrenFirst (core.js:26641)
    at checkAndUpdateView (core.js:37047)
    at callViewAction (core.js:37403)
    at execComponentViewsAction (core.js:37331)
```

Code Sample

HTML:
```html
   <angular-slickgrid gridId="caseListing"
                                       [columnDefinitions]="columnDefinitions"
                                       [gridOptions]="gridOptions"
                                       gridHeight="85vh"
                                       [dataset]="dataSource" 
                        (sgOnSelectedRowsChanged)="onSelectedRowsChanged($event.detail.eventData, $event.detail.args)"
                         (onAngularGridCreated)="angularGridReady($event)">
                    </angular-slickgrid>
```

```ts
@Component({
    selector: 'caseListing',
    templateUrl: './caseListing.component.html',
    styleUrls: ['./caseListing.component.css'],
    animations: [fadeInOut]
})

export class CaseListingComponent {
    angularGrid: AngularGridInstance;
    columnDefinitions: Column[];
    gridOptions: GridOption;

    dataSource: any;
    dataSourceFiltered: any;
    currentFilter = 'None';
    facColumn = {
        id: 'fac', name: 'Facility', field: 'facility', sortable: true, minWidth: 0,
        type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput }
    };

    listingPercent: string = '50%';
    detailPercent: string = '50%';

    constructor(private translate: TranslateService, private endpointService : EndpointFactory, private caseService: CaseService, private apiService: GenericApiService, private global: Globals) {
        this.global.onFacChanged.subscribe(fac => this.onFacChanged(fac));
        this.global.onResChanged.subscribe(resId => this.onResChanged(resId));
    }

    ngOnChanges() {
        this.defineColumns();
        this.defineOptions();
    }

    onFacChanged(fac: any) {
        this.endpointService.getApiData("Main", this.apiService.StringFormat("Cases?FacId={0}&ResId={1}", this.global.currentFac.id, this.global.selectedResId)).subscribe((data: Response) => this.processData(data));
        //slick grid has a bug that if i dont refresh the config each time it remembers old data
        this.ngOnChanges();
    }

    onResChanged(resId: any) {
        this.endpointService.getApiData("Main", this.apiService.StringFormat("Cases?FacId={0}&ResId={1}", this.global.currentFac.id, resId)).subscribe((data: Response) => this.processData(data));
        this.ngOnChanges();
    }

    defineColumns() {
        let that = this;
        this.columnDefinitions = [
            {
                id: 'title', name: 'Case Title', field: 'title', sortable: true, minWidth: 0,
                type: FieldType.string,
                filterable: true, filter: { model: Filters.compoundInput },
                formatter: function (row, cell, value) {
                    if (that.dataSource.length < 1) return '';
                    return "<i class=\"fa fa-circle oval-sm\" aria-hidden=\"true\" style=\"color: " + that.dataSource[row].statusColor + " \"></i> &nbsp;&nbsp;" + value;
                },

            },
            {
                id: 'dates', name: 'Dates', field: 'dates', sortable: true, minWidth: 0,
                type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput }
            },
            {
                id: 'res', name: 'Resident', field: 'resName', sortable: true, minWidth: 0,
                type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput }
            },
            this.facColumn

        ];
        //if currently in a facility no need for the facility column
        if (this.global.currentFac.name)
            this.columnDefinitions = this.columnDefinitions.filter(cd => cd.name != this.facColumn.name);
            //this.columnDefinitions.pop();

    }

    defineOptions() {
        this.gridOptions = {
            autoResize: {
                containerId: 'demo-container'
            },
            fullWidthRows: true,
            rowHeight: 60,
            enableCellNavigation: true,
            enableColumnPicker: true,
            enableExcelCopyBuffer: true,
            enableFiltering: true,
            enableAutoResize: true,
            forceFitColumns: true,
            i18n: this.translate,
        };
    }

    ngOnInit() {
        this.defineColumns();
        this.defineOptions();
        this.onFacChanged(undefined);
    }

    OnSplitterChange() {
        this.angularGrid.resizerService.resizeGrid();
    }

    angularGridReady(angularGrid: any) {
        this.angularGrid = angularGrid;
    }

    left = 50;
    right = 50;
    enlarge(area) {
        if (area == 'left') {
            this.left = 50;
            this.right = 50;
        }
        else {
            this.left = 20;
            this.right = 80;
        }
    }

    processData(data: Response) {
        this.dataSource = data;
        this.dataSourceFiltered = data;
        this.angularGrid.dataView.refresh();
        if (this.currentFilter && this.currentFilter != 'None')
            this.filter(this.currentFilter);
    }

    selectedCaseId;
    onSelectedRowsChanged(e, args) {
        if (args.rows.length > 0) {
            let selectedCase = this.angularGrid.slickGrid.getDataItem(args.rows[0]);
            if (selectedCase) this.selectedCaseId = selectedCase.id;
        }

    }

    filter(status) {
        this.currentFilter = status;
        if (status == 'None')
            this.unfilter();
        else {
            this.dataSource = this.dataSourceFiltered.filter(r => r.status == status);
            this.angularGrid.dataView.refresh();
        }
    }

    unfilter() {
        this.dataSource = this.dataSourceFiltered;
        this.angularGrid.dataView.refresh();
    }
}
```

Included scripts in angular.json:
```json
"node_modules/jquery/dist/jquery.min.js", 
"node_modules/slickgrid/lib/jquery-ui-1.11.3.min.js"
```

Thank you so much,
Daniel

**Comment by ghiscoding** [comment] 2019-08-12 22:35
I really doubt there's anything to do about Angular-Slickgrid itself, there was another user who posted this [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/256) and he did fill in that he's on Angular 8. You didn't mention which Angular you upgrade from.

Also, next time please use the issue template and fill in all the answers, it helps in troubleshooting and resolving issues. The issue #256 is really clear and precise in what that users has.

**Comment by tannenbaums** [comment] 2019-08-12 22:49
Sorry about that. I updated the original comment with all the information I can give.

Thanks again.
P.S. Really enjoying your grid...just hoping to get it to work without downgrading back to 7 :(

**Comment by ghiscoding** [comment] 2019-08-12 22:57
Please use the 3 back ticks (for example ` ```ts ` for TypeScript), it's easier to read. I updated your question with it. 

Your `angular.json` should contain a few libraries, like Flatpickr, SlickGrid itself and few others, did you just not put them your question or did you forget to add them as per the [HOWTO](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step#2-modify-the-angularjson-file) Wiki?

**Comment by tannenbaums** [comment] 2019-08-12 23:13
I did not have all the scripts that are in the wiki, I added them but still getting the same error. OK I guess I can try your suggestion and let you know.

Thanks so much!!

**Comment by tannenbaums** [comment] 2019-08-13 21:10
I ended up downgrading back to angular 7, because I have deadlines and no time to figure this out. Do you want me to keep this open for the future or should I close it?

**Comment by ghiscoding** [comment] 2019-08-13 21:31
Ah sorry to hear that you had to downgrade, let's close it for now and we can reopen it if need be. I'll also stick with Angular 7 for the next few weeks at least. I can refer to this issue if the Angular 8 subject pops up again. Thanks

**Comment by tannenbaums** [comment] 2019-08-13 21:33
Great ty!

**Comment by bocall** [comment] 2019-08-15 12:59
Hi,

I updated the Angular SlickGrid Demo to Angular 8.2.2 and am seeing the same error as posted above.

```
ERROR ReferenceError: preHeaderH is not defined
    at getViewportHeight (:5200/vendor.js:184719)
    at SlickGrid.finishInitialization [as init] (:5200/vendor.js:182308)
    at AngularSlickgridComponent.initialization (:5200/vendor.js:117806)
    at AngularSlickgridComponent.ngAfterViewInit (:5200/vendor.js:117764)
    at callProviderLifecycles (:5200/vendor.js:66723)
    at callElementProvidersLifecycles (:5200/vendor.js:66688)
    at callLifecycleHooksChildrenFirst (:5200/vendor.js:66670)
    at checkAndUpdateView (:5200/vendor.js:77553)
    at callViewAction (:5200/vendor.js:77909)
    at execComponentViewsAction (:5200/vendor.js:77837)
```

I'll downgrade to Angular 7 for now.

**Comment by ghiscoding** [comment] 2019-08-15 13:26
Ok I see now, the problem is (was) that SlickGrid core library had some undeclared variables (missing the `var` in some areas) that it was using. I'm not sure why, but it seems that Angular 7 doesn't care about vendors and Angular 8 cares? I wonder if there's a flag in Angular or TypeScript to disregard these kind of vendor issues (it's in the core lib not my lib). Anyhow, I think you can patch it by specifically using SlickGrid version `2.4.11` (instead of `2.4.9` which Angular-Slickgrid uses in the demos), usually you don't have to add SlickGrid at all to your `package.json` since it's already a dependency of Angular-Slickgrid, but adding latest version would (hopefully) patch the issue.

I am in the middle of adding a new feature and I plan to release this week or early next week. 

@bocall 
Would you mind create a PR (Pull Request) on the new [angular-slickgrid-demos](https://github.com/ghiscoding/angular-slickgrid-demos) repo so that I won't have to redo the work you did to update to Angular 8?

**Comment by bocall** [comment] 2019-08-15 14:55
@ghiscoding I've create a feature for the changes to upgrade from Angular 7 to 8, however, I don't have permissions to push to `https://github.com/ghiscoding/Angular-Slickgrid-demo.git` and I don't seem to be able to fork that repo either to create a pull request from my own fork.

I just ran the following from within the Angular-SlickGrid-Demo:

```
ng update @angular/cli@8.2.2 @angular/core@8.2.2
```

I'm very new to Angular :-)

If you can give me permissions to push my feature I will push the changes up and create a PR.

**Comment by ghiscoding** [comment] 2019-08-15 15:05
@bocall 
You shouldn't have access to the `master` branch but you should have access to create your own branch on any public repos and that is a public repo. Basically just create a branch and you should be able to push, but just to make sure, you do it on the  [angular-slickgrid-demos](https://github.com/ghiscoding/angular-slickgrid-demos) repo (not here in current repo, I have a big feature coming in and that would bring lots of merge conflicts which I want to avoid)

**Comment by bocall** [comment] 2019-08-15 15:17
@ghiscoding 
Quite new to GitHub too. I have created a project from your `Angular-Slickgrid-demo` and a branch `updateToAngular8`. It can be found [here](https://github.com/bocall/Angular-Slickgrid-demo). I'll try and figure out how to create the pull request from there to your repository.

**Comment by ghiscoding** [comment] 2019-08-15 15:21
This [GitHub Help](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) might help you. However, I see that you forked Angular-Slickgrid directly, I would prefer if you fork the [angular-slickgrid-demos](https://github.com/ghiscoding/angular-slickgrid-demos) repo instead. Again I want to avoid having multiple merge conflicts on the main feature I'm working now, also I would prefer to keep Angular-Slickgrid with Angular 7 for the time being.

**Comment by bocall** [comment] 2019-08-15 19:59
I think I finally got the right repository and the pull request in.

**Comment by ghiscoding** [comment] 2019-08-15 20:35
@bocall 
Yes I see the PR in the other repo, good job. Does it work by using the latest SlickGrid version? I saw that I left `"slickgrid": "github:6pac/SlickGrid"` in the `package.json` so in theory it uses the latest code of SlickGrid core, so I only want to merge the PR if the upgrade works. If there is still some errors when running it, then I'll wait for the core to be fixed first.

**Comment by bocall** [comment] 2019-08-15 20:38
@ghiscoding 
No, I'm getting the same error unfortunately. I also included the latest version of slickgrid in package.json for my own project and I'm getting the same error. I was going to fork this repo and see if updating the version of slickgrid works then.

**Comment by ghiscoding** [comment] 2019-08-15 20:43
@bocall 
Are you sure that is the same error? That is almost impossible, since that was fixed on this [line](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L3340) in the core, it now has the `var` prefix, `var preHeaderH = ...`. The only possible explanation could that your lock file (yarn or npm) has the previous version of SlickGrid installed. Maybe the first thing would be to go under `node_modules/slickgrid` and open `slick.grid.js` and scroll to line 3340 and see if you have the `var` prefix... if you don't then it's because of your lock file, basically Yarn/NPM uses the cache as much as possible via the lock file (yarn uses `yarn.lock` and I forgot what NPM uses, `package-lock.json` I think)

**Comment by bocall** [comment] 2019-08-15 21:20
@ghiscoding 
I tested it there again. I blitzed my node_modules folder, updated the version of `slickgrid` to `2.4.11`. When I check in `slick-grid.js` line 3340 has the `var` prefix.
When I run the application it gives me the same error (see below). When I look at line 127769 in `vendor.js` it's the same as line 3340 in `slick-grid.js` but it does not have the `var` prefix.

```
GridBasicComponent.html:7 
ERROR ReferenceError: preHeaderH is not defined
    at getViewportHeight (slick.grid.js:2903)
    at SlickGrid.finishInitialization [as init] (slick.grid.js:492)
    at AngularSlickgridComponent.initialization (angular-slickgrid.js:11983)
    at AngularSlickgridComponent.ngAfterViewInit (angular-slickgrid.js:11941)
    at callProviderLifecycles (core.js:32327)
    at callElementProvidersLifecycles (core.js:32292)
    at callLifecycleHooksChildrenFirst (core.js:32274)
    at checkAndUpdateView (core.js:44280)
    at callViewAction (core.js:44636)
    at execComponentViewsAction (core.js:44564)
```

```
       headerRowH = ( options.showHeaderRow ) ? options.headerRowHeight + getVBoxDelta($headerRowScroller) : 0;
        footerRowH = ( options.showFooterRow ) ? options.footerRowHeight + getVBoxDelta($footerRowScroller) : 0;
        preHeaderH = (options.createPreHeaderPanel && options.showPreHeaderPanel) ? options.preHeaderPanelHeight + getVBoxDelta($preHeaderPanelScroller) : 0;

        viewportH = parseFloat($.css($container[0], "height", true))
          - parseFloat($.css($container[0], "paddingTop", true))
```

I cleared the browser cache just in case it was caching an old version of `slickgrid`

**Comment by ghiscoding** [comment] 2019-08-15 21:35
@bocall 
Try deleting your lock file (`yarn.lock` for Yarn or package-lock.json` for NPM), then re-run `yarn install` or `npm install`, see if you get the latest code. 

If that doesn't work then, the issue might be because Angular-Slickgrid has the version `2.4.9` of SlickGrid as a dependency. If that is the issue, then that will be fixed when I release my new version of Angular-Slickgrid. I did however saym that I expect to release a new version tomorrow or early next week, I still have couple things to do to finish PR #252 that I'm working on.

**Comment by bocall** [comment] 2019-08-15 22:24
@ghiscoding 
Sorry for the delay in getting back to you. I tried removing the `package-lock.json` file and no luck. 

However, in my own project I added `slickgrid@2.4.11` as a dependency. I then copied the contents of  `slickgrid@2.4.11` and and replaced the `slickgrid` under `node_modules` to `angular-slickgrid@2.9.9`.

This initially gave me another error saying that `columnNamesH` is not defined. In the end I went in and adjusted `slick.grid.js` to add a `var` in front of all the variables in that block (see below). After doing this my grid is rendering in the UI without any console errors.

```
        var columnNamesH = ( options.showColumnHeader ) ? parseFloat($.css($headerScroller[0], "height"))
          + getVBoxDelta($headerScroller) : 0;
        var topPanelH = ( options.showTopPanel ) ? options.topPanelHeight + getVBoxDelta($topPanelScroller) : 0;
        var headerRowH = ( options.showHeaderRow ) ? options.headerRowHeight + getVBoxDelta($headerRowScroller) : 0;
        var footerRowH = ( options.showFooterRow ) ? options.footerRowHeight + getVBoxDelta($footerRowScroller) : 0;
        var preHeaderH = (options.createPreHeaderPanel && options.showPreHeaderPanel) ? options.preHeaderPanelHeight + getVBoxDelta($preHeaderPanelScroller) : 0;
```

I hope this helps.

**Comment by bocall** [comment] 2019-08-15 22:30
Quick update. I tried the same with the `angular-slickgrid-demos` and they work too. So it looks like the `slick.grid.js` will need to be update too.

**Comment by ghiscoding** [comment] 2019-08-15 22:31
@bocall 
Thanks for the in depth troubleshooting, looks like there is 2 problems
1. Angular-Slickgrid still uses `2.4.9` and that will be fixed tomorrow or early next week
2. there still missing `var` in `slick.grid.js` and that will have to be fixed in the [6pac/SlickGrid](https://github.com/6pac/SlickGrid)

To address number 2), you could create a PR on that repo or wait for me to push a PR on that repo. Either way, there will be some delays

**Comment by bocall** [comment] 2019-08-15 22:39
@ghiscoding 
Thanks for the quick responses today. I'll try and open a PR with `6pac/SlickGrid` tomorrow to get that additional `var` added.

With these two issues fixed it looks like you'll be sorted for Angular 8.

**Comment by bocall** [comment] 2019-08-15 22:55
PR opened with `6pac/SlickGrid`

**Comment by ghiscoding** [comment] 2019-08-21 14:01
@tannenbaums @bocall 
So for Angular 8, what I found after troubleshooting the PR that @bocall made for the upgrade, is that `ng update` switches the browser/code target to `ES2015` and that doesn't play well with SlickGrid which is all written in plain old javascript. If you edit your `tsconfig.json` file and you switch back the target to `"target": "es5"`, then it's working fine. 

The culprit is this following explanation from Angular 8 team

> Differential loading of modern JavaScript
From Angular 8 onwards, the CLI is going to produce separate bundles for legacy (ES5) and the modern JavaScript bundles (ES2015+), which will be the part of the overall build process.

So I added an [Angular 8 note](https://github.com/ghiscoding/Angular-Slickgrid#angular-8) in the readme.

The complete troubleshoot I've done can be found under the demos [here](https://github.com/ghiscoding/angular-slickgrid-demos/pull/1)

One final note, this might be fixable in the future, but some changes need to be done on the core lib SlickGrid for that to work.

**Closed by ghiscoding** 2019-08-21 14:01 UTC
Labels: core lib, temporary fix

**Comment by tannenbaums** [comment] 2019-08-21 15:47
Great, Thank you!!!

**Comment by ghiscoding** [comment] 2019-08-21 15:57
Make sure to up vote ⭐️ if you like the lib. Thanks 😄

**Comment by tannenbaums** [comment] 2019-08-21 16:21
Does Upvote mean the star button? I have done that long ago...

**Comment by ghiscoding** [comment] 2019-08-21 16:30
Yes... and great thank you 😉

**Comment by ghiscoding** [comment] 2019-08-21 22:48
Side note, I created a PR (you can see the reference just over this post) in the SlickGrid core lib to fully support ES2015 target, I tested it locally and it works. However please note that it might take a few weeks before this is implemented and a new SlickGrid NPM version is out (which I need in order to use in Angular-Slickgrid), but it seems that this would fix all ES2015 issues and we can expect huge benefit by targeting ES2015 (and even more if skip all IE support since that would in theory create a much smaller bundle size). I'll post back when back all the pieces of the puzzle are available... again for now stick with `"target": "ES5"` and you'll be fine.

**Comment by ghiscoding** [comment] 2019-10-02 20:23
NOTE

Latest version of the SlickGrid core library fixed all `ES2015` build errors, you can upgrade to latest version of Angular-Slickgrid [version 2.11.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.11.0) and change back your build target to `ES2015`. The GitHub demos have been updated already and there's no longer any build errors.

**Comment by tannenbaums** [comment] 2019-10-02 20:38
Nice, thank you!

**Comment by bocall** [comment] 2019-10-02 21:27
Excellent, thank you

**Comment by ghiscoding** [comment] 2019-10-02 21:30
@bocall 
Thanks for your time and contributions in updating all the [angular-slickgrid-demos](https://github.com/ghiscoding/angular-slickgrid-demos) to Angular 8, that was/is very welcome. 🚀
