### ISSUE TITLE
Select all checkbox lag

### ISSUE THREAD

**Issue by dktjsp** [ghiscoding/Angular-Slickgrid#613] opened 2020-10-27 16:03 UTC
### Your Environment

| Software                | Version(s) |
| -------------------- | -------- |
| Angular                  | 10.0.2        | 
| Angular-Slickgrid   | 2.22.4        | 
| TypeScript              | 3.9.5       | 

### Describe the Bug

When using the grid option `enableCheckboxSelector` : true and 

`checkboxSelector: {
    hideSelectAllCheckbox: true,
    hideInFilterHeaderRow: true,
    hideInColumnTitleRow: true
  },`

We have the option to check every items with a checkbox in the header, but when we click on it in a huge list , it takes a long time...

### Steps to Reproduce

Enable these options & click on the checkbox in header

### Expected Behavior

It should not take time, I think it must select the rendered items & change others property in respective object as well

### Current Behavior

It lags and take some time, freeze the page main thread

### Possible Solution

I think it must select the rendered items & change others property in respective object as well

### Code Sample

Did not investigate yet

**Comment by ghiscoding** [comment] 2020-10-27 17:16
What you're described is not a bug, it's a side effect of having a huge list. The Row Selections is a plugin [slick.rowselectionmodel](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.rowselectionmodel.js) that was created in the core lib (SlickGrid) and it loops through every single checkbox and toggles the input checkbox. If you have ways to improve that plugin then you'll want to create a Pull Request in the [6pac/SlickGrid](https://github.com/6pac/SlickGrid) fork. The other option you have is to use Local Pagination (pagination with in-memory dataset) that would improve the performance but as it currently stands, it only toggles the selection in current page, there's this [PR](https://github.com/6pac/SlickGrid/pull/545) that we created to make the selection happen across all pages but I don't know when that will get merged and when that happens it will flow to Angular-Slickgrid.

Either way this is handled by the core library (6pac/SlickGrid) and is not directly related to Angular-Slickgrid and again it's not a bug per say, you might want to rethink how you deal with huge dataset/grid. If you have ways to improve then please create a PR on the 6pac/SlickGrid fork

With that saying, I'll close this

**Closed by ghiscoding** 2020-10-27 17:16 UTC
Labels: core lib, question
