### ISSUE TITLE
Resize column not work 

### ISSUE THREAD

**Issue by diegosliver** [ghiscoding/Angular-Slickgrid#207] opened 2019-05-28 01:43 UTC
After I upgrade the version of the component, 2.5.1 to 2.7.0 the Modify Column Size feature is no longer working properly.

I also did some tests with other versions, and any version other than version 2.5.1 shows the error that I sent as GIF.

Could it be some incompatibility with my project?

![erro](https://user-images.githubusercontent.com/5364796/58444916-aa496380-80d0-11e9-8abf-ad7e0a63a0f8.gif)

**Comment by ghiscoding** [comment] 2019-05-28 02:49
oh that seems to be general to everyone. It seems that latest version of SlickGrid (core) has the issue as well, almost 99% sure it is related to this PR [#372](https://github.com/6pac/SlickGrid/pull/372) in core. @loonix did you forget to test that part before creating your PR at the time?

**Comment by loonix** [comment] 2019-05-28 08:41
Hi All, I will need to take a look and see if it is the root of the issue. I think the resize was working with my change, but I don't use it on my current project so not sure... I am going to be busy on the next weeks as I have an exam to make so probably after that I can take a look.

**Comment by diegosliver** [comment] 2019-05-28 08:55
> oh that seems to be general to everyone. It seems that latest version of SlickGrid (core) has the issue as well, almost 99% sure it is related to this PR [#372](https://github.com/6pac/SlickGrid/pull/372) in core. @loonix did you forget to test that part before creating your PR at the time?
> 
> In the mean time you can use `2.6.0`, it shouldn't have that issue.
> 
> Question to you, why you didn't use the new issue template? Did you even see it?

@ghiscoding Sorry for the way I described the problem.

**Comment by ghiscoding** [comment] 2019-05-28 15:27
@diegosliver @loonix 
I can confirm that removing the PR [#372](https://github.com/6pac/SlickGrid/pull/372) in core fixes the issue. 

@loonix 
I think we'll have to rollback that PR in the core lib.

**Comment by ghiscoding** [comment] 2019-05-28 16:31
Create PR [#382](https://github.com/6pac/SlickGrid/pull/382) to rollback the commit breaking the column resize. However and unfortunately, it usually takes a few weeks before any new version is released in SlickGrid core library, so in the meantime it is preferable to use Angular-Slickgrid version `2.6.0`

**Comment by diegosliver** [comment] 2019-05-28 17:46
@ghiscoding thanks for your help. 

I will wait for the new version to be available. 

You want me to end this issue?

**Comment by ghiscoding** [comment] 2019-05-28 17:54
Leave it open, I'll close when the fix is in

**Comment by ghiscoding** [comment] 2019-05-29 15:20
The PR in core got merged but there won't be any new version for a while I assume. So I pushed a temporary fix, which is to use directly the core lib from GitHub (instead of NPM) as a dependcy (like this `"slickgrid": "github:6pac/SlickGrid"`) but this will not work for everyone and is really a last resource. In order to get it working on your side, you need to delete the `slickgrid` entry in your lock file (example `yarn.lock`) or simply delete the lock file and then update to latest version of Angular-Slickgrid and you should get the latest core version as well (coming directly from GitHub instead of NPM).

Like I said earlier, this is really a temporary fix and I pushed `2.7.1` to include that temp fix. 
I will leave this issue open until SlickGrid core releases a new version on NPM, until then this is the way to go (or use `2.6.0` which doesn't have the issue).

**Closed** 2019-06-10 22:21 UTC
Labels: bug, core lib, temporary fix

**Comment by ghiscoding** [comment] 2019-06-10 22:41
Core had a new NPM version released yesterday, so we can now use it in Angular-Slickgrid in version `2.8.1` to have through NPM.
