### ISSUE TITLE
Slickgrid frozen column moves filter grid menu box

### ISSUE THREAD

**Issue by vikas21thakur** [ghiscoding/Angular-Slickgrid#117] opened 2019-01-28 09:56 UTC
First 1 : ![slickgrid_first_column_freezed](https://user-images.githubusercontent.com/32059665/51828131-f2b66780-2310-11e9-9e18-601f0452fc5a.PNG)
Second 2 : ![slickgrid_filter_move_on_freez_column](https://user-images.githubusercontent.com/32059665/51828133-f34efe00-2310-11e9-899f-86a21bdaa66d.PNG)
Third 3 : ![slickgrid_filter_actual](https://user-images.githubusercontent.com/32059665/51828134-f34efe00-2310-11e9-9311-2360d6e98cf8.PNG)

**I'm submitting a bug report**
**I'm submitting a feature request**

* **Angular Version:**
major.minor.patch

* **Library Version:**
major.minor.patch

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
Angular 7

**Current behavior:**
I have frozen the first column of the slick grid but filter box move on freeze column(PFA- 
First 1 , Second 2)

**Code ::**
return this.gridOptions = {
            createFooterRow: false,
            enableAutoResize: true,
            forceFitColumns: false,
            enableAutoSizeColumns: true,
            enableCellNavigation: true,
            enableRowSelection: true,
            alwaysShowVerticalScroll: false,
            frozenColumn: 0,  
            enableRowMoveManager: true,
            enableTextSelectionOnCells: false,
            rowHeight: 25,
            enableFiltering: true,
            gridMenu: {
                iconCssClass: 'fa fa-ellipsis-v',
            },
            rowMoveManager: {
            },
            editable: true,
            enableCheckboxSelector: false,

            rowSelectionOptions: {
                selectActiveRow: true
            },
            enableColumnReorder: true,
            showHeaderRow: false
        };

**Expected/desired behavior:**
Filter box should come on last(Third 3)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by ghiscoding** [comment] 2019-01-28 14:19
It looks like you are using your own CSS styling, perhaps you overwrote some of the default styling? The frozen demo was all good when I tried it I believe. It seems the problem is only showing when you have no data in the grid. Did you put the grid inside a div container? Without a working demo to replicate, it's kinda hard to help you but your styling might be the cause

**Comment by vikas21thakur** [comment] 2019-01-29 11:36
Thanks for the reply!
My Issue is fixed.
My goal is to display visible row counts on vertical scroll event and I have achieved via getViewport() function.

**Comment by ghiscoding** [comment] 2019-01-29 15:38
Ok so I will close this issue then.
If you like the lib you can also up vote ⭐️ 

Thanks for the response

**Closed by ghiscoding** 2019-01-29 15:38 UTC
Labels: needs more info
