### ISSUE TITLE
Frozen columns do not fit in viewport

### ISSUE THREAD

**Issue by Sevdariel** [ghiscoding/Angular-Slickgrid#1214] opened 2023-08-01 12:25 UTC
### Describe the bug

When trying to increase number of frozen columns after expand one of the column width to get max viewPort width with enabled option frozenRightViewportMinWidth new frozen columns are hidden and grid has wrong data.

![image](https://github.com/ghiscoding/Angular-Slickgrid/assets/15120766/fb865ce4-659a-46b8-aa9a-b274266a8832)

After change one of the frozen column width everything return to normal.

### Reproduction

Bug available to repoduce at demo page https://ghiscoding.github.io/Angular-Slickgrid/#/frozen

1. Expand 'Title' column to max width
2. Scroll right viewPort to see 'Finish' column
3. Freeze 'Finish' column

### Expectation

Frozen columns are moved to the left and it's available to horizontaly scroll leftViewPort. 

### Environment Info

```shell
Angular-Slickgrid demo
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/angular-slickgrid/wiki/HOWTO---Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/Angular-Slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/Angular-Slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment] 2023-08-01 13:21
I don't understand what you are trying to do exactly, are you trying to freeze or pin a column that is wider and outside of the viewport? If that is the case you should get an error in the console saying that you cannot and if so that is the expected behavior.

**Comment by ghiscoding** [comment] 2023-08-10 13:05
> It will be any possibility to change this behavior that left viewport horizontal scroll will be usefull?

That is not the typical approach, users don't like to see multiple scrollbar that does the same thing. You can add CSS to also show scrollbar of the left viewport yourself if that is what you want. We will not add any grid option for this

I'm closing this issue since you did not provide any reproduction and you seem to be having problem with resizing outside the viewport which I already said I will not support... Sending a print screen is not a reproduction, so closing

**Closed by ghiscoding** 2023-08-10 13:05 UTC
Labels: needs more info
