### ISSUE TITLE
Copy values from excel - Date format

### ISSUE THREAD

**Issue by loonix** [ghiscoding/Angular-Slickgrid#185] opened 2019-05-14 14:14 UTC
### Your Environment
Angular - 7
Angular-Slickgrid - 2.6.0

### Context
Dates from excel have a format of DD/MM/YYYY,  when copied to datepicker it returns YYYY-MM-DD which is fine but does not get the date correctly, please check the info below:

### Current Behavior
If I add the following dates to the datepicker it gets the correct values
- **2019-09-20, 2018-08-09**
if I copy from excel that per default has a DD/MM/YYYY format it does not work well:
- e.g **22/02/2019** outputs **2022-02-20** instead of **2019-02-20**

### Possible Solution
Not sure if this is the problem
![image](https://user-images.githubusercontent.com/3384277/57704445-d0472080-7659-11e9-8362-1121054e3f42.png)

**Comment by ghiscoding** [comment] 2019-05-14 14:38
I'm assuming the problem is that your Excel is not the same format as what you display in the grid. The library itself does not (and will never) automatically detect the date format. The user has to define in his column definition setup, what he expect to see and use with the library (again there's no auto-detect, which Excel always does and sometime in a really bad way). There's couple of setting in the column definition, the `type` tells the grid what format is in the cell and this is used in the date picker and other areas of the lib (Formatters also use it), the `outputType` is used mainly by the date picker to display the date in a particular format in the date picker (it might be used in the Export to CSV as well). These 2 properties (`type` and `outputType`) will dictate how the date will be transformed, what you highlighted in the code is which format it will use for the date picker and the date shown in the formatter and export. 

So there isn't much we can do with this behavior, I don't really want to do any kind of auto-detect format feature in the lib, because I know for sure that `Moment.js` will throw all kind of warnings in the console if you aren't specifying the format at first. And it's also really hard to detect the date format when the date is something like `04/05/2000`, is that he US or the Euro (metric) format? I live in Canada and the format is such a sensitive subject here, we are so close to US that it's a 50/50 guess on what the user is using (we are supposed to be using metric but our south neighbor doesn't so), I just hate these 2 formats and I also push the ISO format whenever I can.

**Comment by loonix** [comment] 2019-05-14 14:50
I guess then this can be solved by the user to format the date column to YYYY-MM-DD

**Comment by ghiscoding** [comment] 2019-05-14 14:52
The other thing you can do is align your Formatter with the expected date format of Excel. Meaning if you expect Excel to always use the Euro format, then use it as well in your grid and that should work (I think)

**Comment by loonix** [comment] 2019-05-14 15:18
I tried this:

```javascript
type: this.dateEuFormatter,
formatter: this.dateEuFormatter,
```
```javascript
  dateEuFormatter: any = (row: number, cell: number, value: any, columnDef: Column, dataContext: any) => {    
    const FORMAT = 'DD/MM/YYYY';
    const isDateValid = moment(value, FORMAT, false).isValid();
    return (value && isDateValid) ? moment(value).format(FORMAT) : value;
  };
```

if I console log the value it returns for example `Fri Apr 20 2018 00:00:00 GMT+0100 (British Summer Time)`, not sure If I am doing it right.

**Comment by ghiscoding** [comment] 2019-05-14 16:04
I thought I already had the Euro Formatters, we should probably add them (4x of them) eventually. You said that you console log the `value`, but you should console log the `return` output instead, isn't it? Also this always assume that your date input is a valid `Date` object (like a UTC Date).

**Comment by loonix** [comment] 2019-05-15 07:22
As it takes the dates as UTC it makes no sense to change them to EU dates as it will be weird copying dates in one format and then change them to other format

**Comment by ghiscoding** [comment] 2019-05-15 13:28
I mean in your dataset (backend), it has to be a format that can be converted easily to a Date object.

**Comment by ghiscoding** [comment] 2019-05-16 14:38
@loonix 
I just added the Euro Formatters & Sorters, with all their tests suite. 
If you could take a quick look at the PR #190

However, as I was doing the PR, I remembered that there are multiple ways of showing a date, basically not every country displays the date with slashes "/", some might use the dot "." or the dash "-". I'm thinking of adding that later with the new Grid Options [formatterOptions](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/formatterOption.interface.ts) (that I added yesterday in this [PR](https://github.com/ghiscoding/Angular-Slickgrid/pull/187)), with an extra `dateSeparator` option. This new `formatterOptions` (which is used [here](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/models/gridOption.interface.ts#L238) in the GridOption) is meant to be used as a quicker way to set some common settings for all Formatters in the current grid.

**Comment by ghiscoding** [comment] 2019-05-17 19:09
About my last point, I added a [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/7ddd1d5a5c987c83bc9fb645ba2a70e7b6c9ec91) to add a `formatterOptions` to override the default date separator.

Example
```ts
this.gridOptions = {
  enableAutoResize: true,
  formatterOptions: {
    dateSeparator: '.'
  }
}
```

@loonix 
Does that answer all of your questions/issues?

**Comment by loonix** [comment] 2019-05-20 07:38
Hi there, sorry for the delay replying but took a few days off. This sounds good, have to give it a try.

Thanks

**Comment by ghiscoding** [comment] 2019-05-20 17:17
@loonix 
No problem but just so you know, it's merged but not yet released. I might release a new version sometime this week or next week.

**Comment by ghiscoding** [comment] 2019-05-24 18:18
@loonix 
The Date Euro Formatters and `formatterGridOptions` is now released under version [2.7.0](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.7.0). 

Hope that helps in closing your issue.

**Comment by ghiscoding** [comment] 2019-05-29 21:50
@loonix 
Can I close this issue since all Euro Date Formatter got added to the lib?

**Comment by ghiscoding** [comment] 2019-05-31 16:04
I will assume this can be closed, feel free to provide more details if it's still an issue

**Closed by ghiscoding** 2019-05-31 16:04 UTC
Labels: enhancement
